image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - mhutchie.git-graph
    - streetsidesoftware.code-spell-checker
    - Dart-Code.dart-code

tasks:
  - init: dart pub get
  - name: start
    command: dart run ./bin/dart_cloudrun.dart
