image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - mhutchie.git-graph
    - streetsidesoftware.code-spell-checker
    - Dart-Code.dart-code
    - denoland.vscode-deno

tasks:
  - init: |-
      dart pub get
      dart pub get --directory ./packages/narumincho_json
      dart pub get --directory ./packages/narumincho_util
      dart pub get --directory ./packages/simple_dart_code_gen
      dart pub get --directory ./packages/simple_graphql_client_gen
