name: simple_graphql_client_gen
description: simple_graphql_client_gen
repository: https://github.com/narumincho/dart-packages/tree/main/packages/simple_graphql_client_gen
version: "0.9.2"
environment:
  sdk: ">=3.5.0 <4.0.0"
dependencies:
  collection: ^1.17.0
  fast_immutable_collections: ">=10.0.0 <11.0.0"
  http: ">=0.13.6 <2.0.0"
  meta: ">=1.9.1 <2.0.0"
  narumincho_json: ^0.2.0
  narumincho_util: ^0.2.0
  simple_dart_code_gen: ^0.7.0
dev_dependencies:
  test: ^1.24.2
