// Generated by simple_dart_code_gen. Do not edit.
// ignore_for_file: camel_case_types, constant_identifier_names, always_use_package_imports
import 'package:fast_immutable_collections/fast_immutable_collections.dart';
import 'package:meta/meta.dart';
import 'package:simple_graphql_client_gen/graphql_type.dart' as graphql_type;
import 'package:simple_graphql_client_gen/query_string.dart' as query_string;

import './type.dart' as type;

/// データを取得できる. データを取得するのみで, データを変更しない
@immutable
final class Query implements query_string.GraphQLRootObject {
  /// データを取得できる. データを取得するのみで, データを変更しない
  const Query(
    this.fields, {
    this.name = 'Query',
  });
  final IList<Query_Field> fields;

  /// この構造の型につける型の名前. ※同じ名前で違う構造にするとエラーになるので注意!
  final String name;

  /// `Query` を複製する
  @useResult
  Query copyWith({
    IList<Query_Field>? fields,
    String? name,
  }) {
    return Query(
      (fields ?? this.fields),
      name: (name ?? this.name),
    );
  }

  /// `Query` のフィールドを変更したものを新しく返す
  @useResult
  Query updateFields({
    IList<Query_Field> Function(IList<Query_Field> prevFields)? fields,
    String Function(String prevName)? name,
  }) {
    return Query(
      ((fields == null) ? this.fields : fields(this.fields)),
      name: ((name == null) ? this.name : name(this.name)),
    );
  }

  @override
  @useResult
  int get hashCode {
    return Object.hash(
      fields,
      name,
    );
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (((other is Query) && (fields == other.fields)) &&
        (name == other.name));
  }

  @override
  @useResult
  String toString() {
    return 'Query(${fields}, name: ${name}, )';
  }

  @override
  @useResult
  IList<query_string.QueryField> toFieldList() {
    return IList(fields.map((field) {
      return field.toField();
    }));
  }

  @override
  @useResult
  String getTypeName() {
    return name;
  }

  @override
  @useResult
  String getDescription() {
    return 'データを取得できる. データを取得するのみで, データを変更しない';
  }

  @override
  @useResult
  graphql_type.GraphQLRootObjectType getRootObjectType() {
    return graphql_type.GraphQLRootObjectType.query;
  }
}

/// データを取得できる. データを取得するのみで, データを変更しない
@immutable
sealed class Query_Field implements query_string.IntoGraphQLField {
  /// データを取得できる. データを取得するのみで, データを変更しない
  const Query_Field();
}

/// サーバーでの現在時刻を取得する
///
/// type: `DateTime`
@immutable
final class Query_now implements Query_Field {
  /// サーバーでの現在時刻を取得する
  ///
  /// type: `DateTime`
  const Query_now();
  @override
  @useResult
  int get hashCode {
    return Object.hashAll([]);
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (other is Query_now);
  }

  @override
  @useResult
  String toString() {
    return 'Query_now()';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return const query_string.QueryFieldField(
      'now',
      description: 'サーバーでの現在時刻を取得する',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeDateTime(),
        graphql_type.ListType.notList,
        false,
      ),
    );
  }
}

/// 挨拶をする
///
/// type: `String`
@immutable
final class Query_hello implements Query_Field {
  /// 挨拶をする
  ///
  /// type: `String`
  const Query_hello();
  @override
  @useResult
  int get hashCode {
    return Object.hashAll([]);
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (other is Query_hello);
  }

  @override
  @useResult
  String toString() {
    return 'Query_hello()';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return const query_string.QueryFieldField(
      'hello',
      description: '挨拶をする',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeString(),
        graphql_type.ListType.notList,
        false,
      ),
    );
  }
}

/// データを作成、更新ができる
@immutable
final class Mutation implements query_string.GraphQLRootObject {
  /// データを作成、更新ができる
  const Mutation(
    this.fields, {
    this.name = 'Mutation',
  });
  final IList<Mutation_Field> fields;

  /// この構造の型につける型の名前. ※同じ名前で違う構造にするとエラーになるので注意!
  final String name;

  /// `Mutation` を複製する
  @useResult
  Mutation copyWith({
    IList<Mutation_Field>? fields,
    String? name,
  }) {
    return Mutation(
      (fields ?? this.fields),
      name: (name ?? this.name),
    );
  }

  /// `Mutation` のフィールドを変更したものを新しく返す
  @useResult
  Mutation updateFields({
    IList<Mutation_Field> Function(IList<Mutation_Field> prevFields)? fields,
    String Function(String prevName)? name,
  }) {
    return Mutation(
      ((fields == null) ? this.fields : fields(this.fields)),
      name: ((name == null) ? this.name : name(this.name)),
    );
  }

  @override
  @useResult
  int get hashCode {
    return Object.hash(
      fields,
      name,
    );
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (((other is Mutation) && (fields == other.fields)) &&
        (name == other.name));
  }

  @override
  @useResult
  String toString() {
    return 'Mutation(${fields}, name: ${name}, )';
  }

  @override
  @useResult
  IList<query_string.QueryField> toFieldList() {
    return IList(fields.map((field) {
      return field.toField();
    }));
  }

  @override
  @useResult
  String getTypeName() {
    return name;
  }

  @override
  @useResult
  String getDescription() {
    return 'データを作成、更新ができる';
  }

  @override
  @useResult
  graphql_type.GraphQLRootObjectType getRootObjectType() {
    return graphql_type.GraphQLRootObjectType.mutation;
  }
}

/// データを作成、更新ができる
@immutable
sealed class Mutation_Field implements query_string.IntoGraphQLField {
  /// データを作成、更新ができる
  const Mutation_Field();
}

/// サーバーでの現在時刻を取得する
///
/// type: `DateTime`
@immutable
final class Mutation_now implements Mutation_Field {
  /// サーバーでの現在時刻を取得する
  ///
  /// type: `DateTime`
  const Mutation_now();
  @override
  @useResult
  int get hashCode {
    return Object.hashAll([]);
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (other is Mutation_now);
  }

  @override
  @useResult
  String toString() {
    return 'Mutation_now()';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return const query_string.QueryFieldField(
      'now',
      description: 'サーバーでの現在時刻を取得する',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeDateTime(),
        graphql_type.ListType.notList,
        false,
      ),
    );
  }
}

/// A GraphQL Schema defines the capabilities of a GraphQL server. It exposes all available types and directives on the server, as well as the entry points for query, mutation, and subscription operations.
@immutable
final class GraphQL__Schema implements query_string.GraphQLObjectType {
  /// A GraphQL Schema defines the capabilities of a GraphQL server. It exposes all available types and directives on the server, as well as the entry points for query, mutation, and subscription operations.
  const GraphQL__Schema(
    this.fields, {
    this.name = 'GraphQL__Schema',
  });
  final IList<GraphQL__Schema_Field> fields;

  /// この構造の型につける型の名前. ※同じ名前で違う構造にするとエラーになるので注意!
  final String name;

  /// `GraphQL__Schema` を複製する
  @useResult
  GraphQL__Schema copyWith({
    IList<GraphQL__Schema_Field>? fields,
    String? name,
  }) {
    return GraphQL__Schema(
      (fields ?? this.fields),
      name: (name ?? this.name),
    );
  }

  /// `GraphQL__Schema` のフィールドを変更したものを新しく返す
  @useResult
  GraphQL__Schema updateFields({
    IList<GraphQL__Schema_Field> Function(
            IList<GraphQL__Schema_Field> prevFields)?
        fields,
    String Function(String prevName)? name,
  }) {
    return GraphQL__Schema(
      ((fields == null) ? this.fields : fields(this.fields)),
      name: ((name == null) ? this.name : name(this.name)),
    );
  }

  @override
  @useResult
  int get hashCode {
    return Object.hash(
      fields,
      name,
    );
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (((other is GraphQL__Schema) && (fields == other.fields)) &&
        (name == other.name));
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Schema(${fields}, name: ${name}, )';
  }

  @override
  @useResult
  IList<query_string.QueryField> toFieldList() {
    return IList(fields.map((field) {
      return field.toField();
    }));
  }

  @override
  @useResult
  String getTypeName() {
    return name;
  }

  @override
  @useResult
  String getDescription() {
    return 'A GraphQL Schema defines the capabilities of a GraphQL server. It exposes all available types and directives on the server, as well as the entry points for query, mutation, and subscription operations.';
  }
}

/// A GraphQL Schema defines the capabilities of a GraphQL server. It exposes all available types and directives on the server, as well as the entry points for query, mutation, and subscription operations.
@immutable
sealed class GraphQL__Schema_Field implements query_string.IntoGraphQLField {
  /// A GraphQL Schema defines the capabilities of a GraphQL server. It exposes all available types and directives on the server, as well as the entry points for query, mutation, and subscription operations.
  const GraphQL__Schema_Field();
}

///
///
/// type: `String?`
@immutable
final class GraphQL__Schema_description implements GraphQL__Schema_Field {
  ///
  ///
  /// type: `String?`
  const GraphQL__Schema_description();
  @override
  @useResult
  int get hashCode {
    return Object.hashAll([]);
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (other is GraphQL__Schema_description);
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Schema_description()';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return const query_string.QueryFieldField(
      'description',
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeString(),
        graphql_type.ListType.notList,
        true,
      ),
    );
  }
}

/// A list of all types supported by this server.
///
/// type: `IList<type.GraphQL__Type>`
@immutable
final class GraphQL__Schema_types implements GraphQL__Schema_Field {
  /// A list of all types supported by this server.
  ///
  /// type: `IList<type.GraphQL__Type>`
  const GraphQL__Schema_types(
    this.return_,
  );
  final GraphQL__Type return_;

  /// `GraphQL__Schema_types` を複製する
  @useResult
  GraphQL__Schema_types copyWith({
    GraphQL__Type? return_,
  }) {
    return GraphQL__Schema_types((return_ ?? this.return_));
  }

  /// `GraphQL__Schema_types` のフィールドを変更したものを新しく返す
  @useResult
  GraphQL__Schema_types updateFields({
    GraphQL__Type Function(GraphQL__Type prevReturn_)? return_,
  }) {
    return GraphQL__Schema_types(
        ((return_ == null) ? this.return_ : return_(this.return_)));
  }

  @override
  @useResult
  int get hashCode {
    return return_.hashCode;
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return ((other is GraphQL__Schema_types) && (return_ == other.return_));
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Schema_types(${return_}, )';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return query_string.QueryFieldField(
      'types',
      description: 'A list of all types supported by this server.',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeObject(return_),
        graphql_type.ListType.list,
        false,
      ),
    );
  }
}

/// The type that query operations will be rooted at.
///
/// type: `type.GraphQL__Type`
@immutable
final class GraphQL__Schema_queryType implements GraphQL__Schema_Field {
  /// The type that query operations will be rooted at.
  ///
  /// type: `type.GraphQL__Type`
  const GraphQL__Schema_queryType(
    this.return_,
  );
  final GraphQL__Type return_;

  /// `GraphQL__Schema_queryType` を複製する
  @useResult
  GraphQL__Schema_queryType copyWith({
    GraphQL__Type? return_,
  }) {
    return GraphQL__Schema_queryType((return_ ?? this.return_));
  }

  /// `GraphQL__Schema_queryType` のフィールドを変更したものを新しく返す
  @useResult
  GraphQL__Schema_queryType updateFields({
    GraphQL__Type Function(GraphQL__Type prevReturn_)? return_,
  }) {
    return GraphQL__Schema_queryType(
        ((return_ == null) ? this.return_ : return_(this.return_)));
  }

  @override
  @useResult
  int get hashCode {
    return return_.hashCode;
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return ((other is GraphQL__Schema_queryType) && (return_ == other.return_));
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Schema_queryType(${return_}, )';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return query_string.QueryFieldField(
      'queryType',
      description: 'The type that query operations will be rooted at.',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeObject(return_),
        graphql_type.ListType.notList,
        false,
      ),
    );
  }
}

/// If this server supports mutation, the type that mutation operations will be rooted at.
///
/// type: `type.GraphQL__Type?`
@immutable
final class GraphQL__Schema_mutationType implements GraphQL__Schema_Field {
  /// If this server supports mutation, the type that mutation operations will be rooted at.
  ///
  /// type: `type.GraphQL__Type?`
  const GraphQL__Schema_mutationType(
    this.return_,
  );
  final GraphQL__Type return_;

  /// `GraphQL__Schema_mutationType` を複製する
  @useResult
  GraphQL__Schema_mutationType copyWith({
    GraphQL__Type? return_,
  }) {
    return GraphQL__Schema_mutationType((return_ ?? this.return_));
  }

  /// `GraphQL__Schema_mutationType` のフィールドを変更したものを新しく返す
  @useResult
  GraphQL__Schema_mutationType updateFields({
    GraphQL__Type Function(GraphQL__Type prevReturn_)? return_,
  }) {
    return GraphQL__Schema_mutationType(
        ((return_ == null) ? this.return_ : return_(this.return_)));
  }

  @override
  @useResult
  int get hashCode {
    return return_.hashCode;
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return ((other is GraphQL__Schema_mutationType) &&
        (return_ == other.return_));
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Schema_mutationType(${return_}, )';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return query_string.QueryFieldField(
      'mutationType',
      description:
          'If this server supports mutation, the type that mutation operations will be rooted at.',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeObject(return_),
        graphql_type.ListType.notList,
        true,
      ),
    );
  }
}

/// If this server support subscription, the type that subscription operations will be rooted at.
///
/// type: `type.GraphQL__Type?`
@immutable
final class GraphQL__Schema_subscriptionType implements GraphQL__Schema_Field {
  /// If this server support subscription, the type that subscription operations will be rooted at.
  ///
  /// type: `type.GraphQL__Type?`
  const GraphQL__Schema_subscriptionType(
    this.return_,
  );
  final GraphQL__Type return_;

  /// `GraphQL__Schema_subscriptionType` を複製する
  @useResult
  GraphQL__Schema_subscriptionType copyWith({
    GraphQL__Type? return_,
  }) {
    return GraphQL__Schema_subscriptionType((return_ ?? this.return_));
  }

  /// `GraphQL__Schema_subscriptionType` のフィールドを変更したものを新しく返す
  @useResult
  GraphQL__Schema_subscriptionType updateFields({
    GraphQL__Type Function(GraphQL__Type prevReturn_)? return_,
  }) {
    return GraphQL__Schema_subscriptionType(
        ((return_ == null) ? this.return_ : return_(this.return_)));
  }

  @override
  @useResult
  int get hashCode {
    return return_.hashCode;
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return ((other is GraphQL__Schema_subscriptionType) &&
        (return_ == other.return_));
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Schema_subscriptionType(${return_}, )';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return query_string.QueryFieldField(
      'subscriptionType',
      description:
          'If this server support subscription, the type that subscription operations will be rooted at.',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeObject(return_),
        graphql_type.ListType.notList,
        true,
      ),
    );
  }
}

/// A list of all directives supported by this server.
///
/// type: `IList<type.GraphQL__Directive>`
@immutable
final class GraphQL__Schema_directives implements GraphQL__Schema_Field {
  /// A list of all directives supported by this server.
  ///
  /// type: `IList<type.GraphQL__Directive>`
  const GraphQL__Schema_directives(
    this.return_,
  );
  final GraphQL__Directive return_;

  /// `GraphQL__Schema_directives` を複製する
  @useResult
  GraphQL__Schema_directives copyWith({
    GraphQL__Directive? return_,
  }) {
    return GraphQL__Schema_directives((return_ ?? this.return_));
  }

  /// `GraphQL__Schema_directives` のフィールドを変更したものを新しく返す
  @useResult
  GraphQL__Schema_directives updateFields({
    GraphQL__Directive Function(GraphQL__Directive prevReturn_)? return_,
  }) {
    return GraphQL__Schema_directives(
        ((return_ == null) ? this.return_ : return_(this.return_)));
  }

  @override
  @useResult
  int get hashCode {
    return return_.hashCode;
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return ((other is GraphQL__Schema_directives) &&
        (return_ == other.return_));
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Schema_directives(${return_}, )';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return query_string.QueryFieldField(
      'directives',
      description: 'A list of all directives supported by this server.',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeObject(return_),
        graphql_type.ListType.list,
        false,
      ),
    );
  }
}

/// The fundamental unit of any GraphQL Schema is the type. There are many kinds of types in GraphQL as represented by the `__TypeKind` enum.
///
/// Depending on the kind of a type, certain fields describe information about that type. Scalar types provide no information beyond a name, description and optional `specifiedByURL`, while Enum types provide their values. Object and Interface types provide the fields they describe. Abstract types, Union and Interface, provide the Object types possible at runtime. List and NonNull types compose other types.
@immutable
final class GraphQL__Type implements query_string.GraphQLObjectType {
  /// The fundamental unit of any GraphQL Schema is the type. There are many kinds of types in GraphQL as represented by the `__TypeKind` enum.
  ///
  /// Depending on the kind of a type, certain fields describe information about that type. Scalar types provide no information beyond a name, description and optional `specifiedByURL`, while Enum types provide their values. Object and Interface types provide the fields they describe. Abstract types, Union and Interface, provide the Object types possible at runtime. List and NonNull types compose other types.
  const GraphQL__Type(
    this.fields, {
    this.name = 'GraphQL__Type',
  });
  final IList<GraphQL__Type_Field> fields;

  /// この構造の型につける型の名前. ※同じ名前で違う構造にするとエラーになるので注意!
  final String name;

  /// `GraphQL__Type` を複製する
  @useResult
  GraphQL__Type copyWith({
    IList<GraphQL__Type_Field>? fields,
    String? name,
  }) {
    return GraphQL__Type(
      (fields ?? this.fields),
      name: (name ?? this.name),
    );
  }

  /// `GraphQL__Type` のフィールドを変更したものを新しく返す
  @useResult
  GraphQL__Type updateFields({
    IList<GraphQL__Type_Field> Function(IList<GraphQL__Type_Field> prevFields)?
        fields,
    String Function(String prevName)? name,
  }) {
    return GraphQL__Type(
      ((fields == null) ? this.fields : fields(this.fields)),
      name: ((name == null) ? this.name : name(this.name)),
    );
  }

  @override
  @useResult
  int get hashCode {
    return Object.hash(
      fields,
      name,
    );
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (((other is GraphQL__Type) && (fields == other.fields)) &&
        (name == other.name));
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Type(${fields}, name: ${name}, )';
  }

  @override
  @useResult
  IList<query_string.QueryField> toFieldList() {
    return IList(fields.map((field) {
      return field.toField();
    }));
  }

  @override
  @useResult
  String getTypeName() {
    return name;
  }

  @override
  @useResult
  String getDescription() {
    return 'The fundamental unit of any GraphQL Schema is the type. There are many kinds of types in GraphQL as represented by the `__TypeKind` enum.\n\nDepending on the kind of a type, certain fields describe information about that type. Scalar types provide no information beyond a name, description and optional `specifiedByURL`, while Enum types provide their values. Object and Interface types provide the fields they describe. Abstract types, Union and Interface, provide the Object types possible at runtime. List and NonNull types compose other types.';
  }
}

/// The fundamental unit of any GraphQL Schema is the type. There are many kinds of types in GraphQL as represented by the `__TypeKind` enum.
///
/// Depending on the kind of a type, certain fields describe information about that type. Scalar types provide no information beyond a name, description and optional `specifiedByURL`, while Enum types provide their values. Object and Interface types provide the fields they describe. Abstract types, Union and Interface, provide the Object types possible at runtime. List and NonNull types compose other types.
@immutable
sealed class GraphQL__Type_Field implements query_string.IntoGraphQLField {
  /// The fundamental unit of any GraphQL Schema is the type. There are many kinds of types in GraphQL as represented by the `__TypeKind` enum.
  ///
  /// Depending on the kind of a type, certain fields describe information about that type. Scalar types provide no information beyond a name, description and optional `specifiedByURL`, while Enum types provide their values. Object and Interface types provide the fields they describe. Abstract types, Union and Interface, provide the Object types possible at runtime. List and NonNull types compose other types.
  const GraphQL__Type_Field();
}

///
///
/// type: `type.GraphQL__TypeKind`
@immutable
final class GraphQL__Type_kind implements GraphQL__Type_Field {
  ///
  ///
  /// type: `type.GraphQL__TypeKind`
  const GraphQL__Type_kind();
  @override
  @useResult
  int get hashCode {
    return Object.hashAll([]);
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (other is GraphQL__Type_kind);
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Type_kind()';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return const query_string.QueryFieldField(
      'kind',
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeNotObject('__TypeKind'),
        graphql_type.ListType.notList,
        false,
      ),
    );
  }
}

///
///
/// type: `String?`
@immutable
final class GraphQL__Type_name implements GraphQL__Type_Field {
  ///
  ///
  /// type: `String?`
  const GraphQL__Type_name();
  @override
  @useResult
  int get hashCode {
    return Object.hashAll([]);
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (other is GraphQL__Type_name);
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Type_name()';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return const query_string.QueryFieldField(
      'name',
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeString(),
        graphql_type.ListType.notList,
        true,
      ),
    );
  }
}

///
///
/// type: `String?`
@immutable
final class GraphQL__Type_description implements GraphQL__Type_Field {
  ///
  ///
  /// type: `String?`
  const GraphQL__Type_description();
  @override
  @useResult
  int get hashCode {
    return Object.hashAll([]);
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (other is GraphQL__Type_description);
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Type_description()';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return const query_string.QueryFieldField(
      'description',
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeString(),
        graphql_type.ListType.notList,
        true,
      ),
    );
  }
}

///
///
/// type: `String?`
@immutable
final class GraphQL__Type_specifiedByURL implements GraphQL__Type_Field {
  ///
  ///
  /// type: `String?`
  const GraphQL__Type_specifiedByURL();
  @override
  @useResult
  int get hashCode {
    return Object.hashAll([]);
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (other is GraphQL__Type_specifiedByURL);
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Type_specifiedByURL()';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return const query_string.QueryFieldField(
      'specifiedByURL',
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeString(),
        graphql_type.ListType.notList,
        true,
      ),
    );
  }
}

///
///
/// type: `IList<type.GraphQL__Field>?`
@immutable
final class GraphQL__Type_fields implements GraphQL__Type_Field {
  ///
  ///
  /// type: `IList<type.GraphQL__Field>?`
  const GraphQL__Type_fields(
    this.return_, {
    this.includeDeprecated = const query_string.StaticValue(null),
  });
  final query_string.VariableOrStaticValue<bool?> includeDeprecated;

  final GraphQL__Field return_;

  /// `GraphQL__Type_fields` を複製する
  @useResult
  GraphQL__Type_fields copyWith({
    query_string.VariableOrStaticValue<bool?>? includeDeprecated,
    GraphQL__Field? return_,
  }) {
    return GraphQL__Type_fields(
      (return_ ?? this.return_),
      includeDeprecated: (includeDeprecated ?? this.includeDeprecated),
    );
  }

  /// `GraphQL__Type_fields` のフィールドを変更したものを新しく返す
  @useResult
  GraphQL__Type_fields updateFields({
    query_string.VariableOrStaticValue<bool?> Function(
            query_string.VariableOrStaticValue<bool?> prevIncludeDeprecated)?
        includeDeprecated,
    GraphQL__Field Function(GraphQL__Field prevReturn_)? return_,
  }) {
    return GraphQL__Type_fields(
      ((return_ == null) ? this.return_ : return_(this.return_)),
      includeDeprecated: ((includeDeprecated == null)
          ? this.includeDeprecated
          : includeDeprecated(this.includeDeprecated)),
    );
  }

  @override
  @useResult
  int get hashCode {
    return Object.hash(
      includeDeprecated,
      return_,
    );
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (((other is GraphQL__Type_fields) &&
            (includeDeprecated == other.includeDeprecated)) &&
        (return_ == other.return_));
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Type_fields(${return_}, includeDeprecated: ${includeDeprecated}, )';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return query_string.QueryFieldField(
      'fields',
      args: IList([
        query_string.QueryFieldArg(
          name: 'includeDeprecated',
          input: includeDeprecatedToQueryInput(),
        )
      ]),
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeObject(return_),
        graphql_type.ListType.list,
        true,
      ),
    );
  }

  @useResult
  query_string.QueryInput includeDeprecatedToQueryInput() {
    return includeDeprecated.toQueryInput(
      type: const graphql_type.GraphQLType(
        name: 'Boolean',
        isNullable: true,
        listType: graphql_type.ListType.notList,
      ),
      staticValueToQueryInputFunc: (staticValue) {
        return (switch (staticValue) {
          null => const query_string.QueryInputNull(),
          final nonNull => query_string.QueryInputBoolean(nonNull),
        });
      },
    );
  }
}

///
///
/// type: `IList<type.GraphQL__Type>?`
@immutable
final class GraphQL__Type_interfaces implements GraphQL__Type_Field {
  ///
  ///
  /// type: `IList<type.GraphQL__Type>?`
  const GraphQL__Type_interfaces(
    this.return_,
  );
  final GraphQL__Type return_;

  /// `GraphQL__Type_interfaces` を複製する
  @useResult
  GraphQL__Type_interfaces copyWith({
    GraphQL__Type? return_,
  }) {
    return GraphQL__Type_interfaces((return_ ?? this.return_));
  }

  /// `GraphQL__Type_interfaces` のフィールドを変更したものを新しく返す
  @useResult
  GraphQL__Type_interfaces updateFields({
    GraphQL__Type Function(GraphQL__Type prevReturn_)? return_,
  }) {
    return GraphQL__Type_interfaces(
        ((return_ == null) ? this.return_ : return_(this.return_)));
  }

  @override
  @useResult
  int get hashCode {
    return return_.hashCode;
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return ((other is GraphQL__Type_interfaces) && (return_ == other.return_));
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Type_interfaces(${return_}, )';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return query_string.QueryFieldField(
      'interfaces',
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeObject(return_),
        graphql_type.ListType.list,
        true,
      ),
    );
  }
}

///
///
/// type: `IList<type.GraphQL__Type>?`
@immutable
final class GraphQL__Type_possibleTypes implements GraphQL__Type_Field {
  ///
  ///
  /// type: `IList<type.GraphQL__Type>?`
  const GraphQL__Type_possibleTypes(
    this.return_,
  );
  final GraphQL__Type return_;

  /// `GraphQL__Type_possibleTypes` を複製する
  @useResult
  GraphQL__Type_possibleTypes copyWith({
    GraphQL__Type? return_,
  }) {
    return GraphQL__Type_possibleTypes((return_ ?? this.return_));
  }

  /// `GraphQL__Type_possibleTypes` のフィールドを変更したものを新しく返す
  @useResult
  GraphQL__Type_possibleTypes updateFields({
    GraphQL__Type Function(GraphQL__Type prevReturn_)? return_,
  }) {
    return GraphQL__Type_possibleTypes(
        ((return_ == null) ? this.return_ : return_(this.return_)));
  }

  @override
  @useResult
  int get hashCode {
    return return_.hashCode;
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return ((other is GraphQL__Type_possibleTypes) &&
        (return_ == other.return_));
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Type_possibleTypes(${return_}, )';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return query_string.QueryFieldField(
      'possibleTypes',
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeObject(return_),
        graphql_type.ListType.list,
        true,
      ),
    );
  }
}

///
///
/// type: `IList<type.GraphQL__EnumValue>?`
@immutable
final class GraphQL__Type_enumValues implements GraphQL__Type_Field {
  ///
  ///
  /// type: `IList<type.GraphQL__EnumValue>?`
  const GraphQL__Type_enumValues(
    this.return_, {
    this.includeDeprecated = const query_string.StaticValue(null),
  });
  final query_string.VariableOrStaticValue<bool?> includeDeprecated;

  final GraphQL__EnumValue return_;

  /// `GraphQL__Type_enumValues` を複製する
  @useResult
  GraphQL__Type_enumValues copyWith({
    query_string.VariableOrStaticValue<bool?>? includeDeprecated,
    GraphQL__EnumValue? return_,
  }) {
    return GraphQL__Type_enumValues(
      (return_ ?? this.return_),
      includeDeprecated: (includeDeprecated ?? this.includeDeprecated),
    );
  }

  /// `GraphQL__Type_enumValues` のフィールドを変更したものを新しく返す
  @useResult
  GraphQL__Type_enumValues updateFields({
    query_string.VariableOrStaticValue<bool?> Function(
            query_string.VariableOrStaticValue<bool?> prevIncludeDeprecated)?
        includeDeprecated,
    GraphQL__EnumValue Function(GraphQL__EnumValue prevReturn_)? return_,
  }) {
    return GraphQL__Type_enumValues(
      ((return_ == null) ? this.return_ : return_(this.return_)),
      includeDeprecated: ((includeDeprecated == null)
          ? this.includeDeprecated
          : includeDeprecated(this.includeDeprecated)),
    );
  }

  @override
  @useResult
  int get hashCode {
    return Object.hash(
      includeDeprecated,
      return_,
    );
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (((other is GraphQL__Type_enumValues) &&
            (includeDeprecated == other.includeDeprecated)) &&
        (return_ == other.return_));
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Type_enumValues(${return_}, includeDeprecated: ${includeDeprecated}, )';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return query_string.QueryFieldField(
      'enumValues',
      args: IList([
        query_string.QueryFieldArg(
          name: 'includeDeprecated',
          input: includeDeprecatedToQueryInput(),
        )
      ]),
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeObject(return_),
        graphql_type.ListType.list,
        true,
      ),
    );
  }

  @useResult
  query_string.QueryInput includeDeprecatedToQueryInput() {
    return includeDeprecated.toQueryInput(
      type: const graphql_type.GraphQLType(
        name: 'Boolean',
        isNullable: true,
        listType: graphql_type.ListType.notList,
      ),
      staticValueToQueryInputFunc: (staticValue) {
        return (switch (staticValue) {
          null => const query_string.QueryInputNull(),
          final nonNull => query_string.QueryInputBoolean(nonNull),
        });
      },
    );
  }
}

///
///
/// type: `IList<type.GraphQL__InputValue>?`
@immutable
final class GraphQL__Type_inputFields implements GraphQL__Type_Field {
  ///
  ///
  /// type: `IList<type.GraphQL__InputValue>?`
  const GraphQL__Type_inputFields(
    this.return_, {
    this.includeDeprecated = const query_string.StaticValue(null),
  });
  final query_string.VariableOrStaticValue<bool?> includeDeprecated;

  final GraphQL__InputValue return_;

  /// `GraphQL__Type_inputFields` を複製する
  @useResult
  GraphQL__Type_inputFields copyWith({
    query_string.VariableOrStaticValue<bool?>? includeDeprecated,
    GraphQL__InputValue? return_,
  }) {
    return GraphQL__Type_inputFields(
      (return_ ?? this.return_),
      includeDeprecated: (includeDeprecated ?? this.includeDeprecated),
    );
  }

  /// `GraphQL__Type_inputFields` のフィールドを変更したものを新しく返す
  @useResult
  GraphQL__Type_inputFields updateFields({
    query_string.VariableOrStaticValue<bool?> Function(
            query_string.VariableOrStaticValue<bool?> prevIncludeDeprecated)?
        includeDeprecated,
    GraphQL__InputValue Function(GraphQL__InputValue prevReturn_)? return_,
  }) {
    return GraphQL__Type_inputFields(
      ((return_ == null) ? this.return_ : return_(this.return_)),
      includeDeprecated: ((includeDeprecated == null)
          ? this.includeDeprecated
          : includeDeprecated(this.includeDeprecated)),
    );
  }

  @override
  @useResult
  int get hashCode {
    return Object.hash(
      includeDeprecated,
      return_,
    );
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (((other is GraphQL__Type_inputFields) &&
            (includeDeprecated == other.includeDeprecated)) &&
        (return_ == other.return_));
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Type_inputFields(${return_}, includeDeprecated: ${includeDeprecated}, )';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return query_string.QueryFieldField(
      'inputFields',
      args: IList([
        query_string.QueryFieldArg(
          name: 'includeDeprecated',
          input: includeDeprecatedToQueryInput(),
        )
      ]),
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeObject(return_),
        graphql_type.ListType.list,
        true,
      ),
    );
  }

  @useResult
  query_string.QueryInput includeDeprecatedToQueryInput() {
    return includeDeprecated.toQueryInput(
      type: const graphql_type.GraphQLType(
        name: 'Boolean',
        isNullable: true,
        listType: graphql_type.ListType.notList,
      ),
      staticValueToQueryInputFunc: (staticValue) {
        return (switch (staticValue) {
          null => const query_string.QueryInputNull(),
          final nonNull => query_string.QueryInputBoolean(nonNull),
        });
      },
    );
  }
}

///
///
/// type: `type.GraphQL__Type?`
@immutable
final class GraphQL__Type_ofType implements GraphQL__Type_Field {
  ///
  ///
  /// type: `type.GraphQL__Type?`
  const GraphQL__Type_ofType(
    this.return_,
  );
  final GraphQL__Type return_;

  /// `GraphQL__Type_ofType` を複製する
  @useResult
  GraphQL__Type_ofType copyWith({
    GraphQL__Type? return_,
  }) {
    return GraphQL__Type_ofType((return_ ?? this.return_));
  }

  /// `GraphQL__Type_ofType` のフィールドを変更したものを新しく返す
  @useResult
  GraphQL__Type_ofType updateFields({
    GraphQL__Type Function(GraphQL__Type prevReturn_)? return_,
  }) {
    return GraphQL__Type_ofType(
        ((return_ == null) ? this.return_ : return_(this.return_)));
  }

  @override
  @useResult
  int get hashCode {
    return return_.hashCode;
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return ((other is GraphQL__Type_ofType) && (return_ == other.return_));
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Type_ofType(${return_}, )';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return query_string.QueryFieldField(
      'ofType',
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeObject(return_),
        graphql_type.ListType.notList,
        true,
      ),
    );
  }
}

/// Object and Interface types are described by a list of Fields, each of which has a name, potentially a list of arguments, and a return type.
@immutable
final class GraphQL__Field implements query_string.GraphQLObjectType {
  /// Object and Interface types are described by a list of Fields, each of which has a name, potentially a list of arguments, and a return type.
  const GraphQL__Field(
    this.fields, {
    this.name = 'GraphQL__Field',
  });
  final IList<GraphQL__Field_Field> fields;

  /// この構造の型につける型の名前. ※同じ名前で違う構造にするとエラーになるので注意!
  final String name;

  /// `GraphQL__Field` を複製する
  @useResult
  GraphQL__Field copyWith({
    IList<GraphQL__Field_Field>? fields,
    String? name,
  }) {
    return GraphQL__Field(
      (fields ?? this.fields),
      name: (name ?? this.name),
    );
  }

  /// `GraphQL__Field` のフィールドを変更したものを新しく返す
  @useResult
  GraphQL__Field updateFields({
    IList<GraphQL__Field_Field> Function(
            IList<GraphQL__Field_Field> prevFields)?
        fields,
    String Function(String prevName)? name,
  }) {
    return GraphQL__Field(
      ((fields == null) ? this.fields : fields(this.fields)),
      name: ((name == null) ? this.name : name(this.name)),
    );
  }

  @override
  @useResult
  int get hashCode {
    return Object.hash(
      fields,
      name,
    );
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (((other is GraphQL__Field) && (fields == other.fields)) &&
        (name == other.name));
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Field(${fields}, name: ${name}, )';
  }

  @override
  @useResult
  IList<query_string.QueryField> toFieldList() {
    return IList(fields.map((field) {
      return field.toField();
    }));
  }

  @override
  @useResult
  String getTypeName() {
    return name;
  }

  @override
  @useResult
  String getDescription() {
    return 'Object and Interface types are described by a list of Fields, each of which has a name, potentially a list of arguments, and a return type.';
  }
}

/// Object and Interface types are described by a list of Fields, each of which has a name, potentially a list of arguments, and a return type.
@immutable
sealed class GraphQL__Field_Field implements query_string.IntoGraphQLField {
  /// Object and Interface types are described by a list of Fields, each of which has a name, potentially a list of arguments, and a return type.
  const GraphQL__Field_Field();
}

///
///
/// type: `String`
@immutable
final class GraphQL__Field_name implements GraphQL__Field_Field {
  ///
  ///
  /// type: `String`
  const GraphQL__Field_name();
  @override
  @useResult
  int get hashCode {
    return Object.hashAll([]);
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (other is GraphQL__Field_name);
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Field_name()';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return const query_string.QueryFieldField(
      'name',
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeString(),
        graphql_type.ListType.notList,
        false,
      ),
    );
  }
}

///
///
/// type: `String?`
@immutable
final class GraphQL__Field_description implements GraphQL__Field_Field {
  ///
  ///
  /// type: `String?`
  const GraphQL__Field_description();
  @override
  @useResult
  int get hashCode {
    return Object.hashAll([]);
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (other is GraphQL__Field_description);
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Field_description()';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return const query_string.QueryFieldField(
      'description',
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeString(),
        graphql_type.ListType.notList,
        true,
      ),
    );
  }
}

///
///
/// type: `IList<type.GraphQL__InputValue>`
@immutable
final class GraphQL__Field_args implements GraphQL__Field_Field {
  ///
  ///
  /// type: `IList<type.GraphQL__InputValue>`
  const GraphQL__Field_args(
    this.return_, {
    this.includeDeprecated = const query_string.StaticValue(null),
  });
  final query_string.VariableOrStaticValue<bool?> includeDeprecated;

  final GraphQL__InputValue return_;

  /// `GraphQL__Field_args` を複製する
  @useResult
  GraphQL__Field_args copyWith({
    query_string.VariableOrStaticValue<bool?>? includeDeprecated,
    GraphQL__InputValue? return_,
  }) {
    return GraphQL__Field_args(
      (return_ ?? this.return_),
      includeDeprecated: (includeDeprecated ?? this.includeDeprecated),
    );
  }

  /// `GraphQL__Field_args` のフィールドを変更したものを新しく返す
  @useResult
  GraphQL__Field_args updateFields({
    query_string.VariableOrStaticValue<bool?> Function(
            query_string.VariableOrStaticValue<bool?> prevIncludeDeprecated)?
        includeDeprecated,
    GraphQL__InputValue Function(GraphQL__InputValue prevReturn_)? return_,
  }) {
    return GraphQL__Field_args(
      ((return_ == null) ? this.return_ : return_(this.return_)),
      includeDeprecated: ((includeDeprecated == null)
          ? this.includeDeprecated
          : includeDeprecated(this.includeDeprecated)),
    );
  }

  @override
  @useResult
  int get hashCode {
    return Object.hash(
      includeDeprecated,
      return_,
    );
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (((other is GraphQL__Field_args) &&
            (includeDeprecated == other.includeDeprecated)) &&
        (return_ == other.return_));
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Field_args(${return_}, includeDeprecated: ${includeDeprecated}, )';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return query_string.QueryFieldField(
      'args',
      args: IList([
        query_string.QueryFieldArg(
          name: 'includeDeprecated',
          input: includeDeprecatedToQueryInput(),
        )
      ]),
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeObject(return_),
        graphql_type.ListType.list,
        false,
      ),
    );
  }

  @useResult
  query_string.QueryInput includeDeprecatedToQueryInput() {
    return includeDeprecated.toQueryInput(
      type: const graphql_type.GraphQLType(
        name: 'Boolean',
        isNullable: true,
        listType: graphql_type.ListType.notList,
      ),
      staticValueToQueryInputFunc: (staticValue) {
        return (switch (staticValue) {
          null => const query_string.QueryInputNull(),
          final nonNull => query_string.QueryInputBoolean(nonNull),
        });
      },
    );
  }
}

///
///
/// type: `type.GraphQL__Type`
@immutable
final class GraphQL__Field_type implements GraphQL__Field_Field {
  ///
  ///
  /// type: `type.GraphQL__Type`
  const GraphQL__Field_type(
    this.return_,
  );
  final GraphQL__Type return_;

  /// `GraphQL__Field_type` を複製する
  @useResult
  GraphQL__Field_type copyWith({
    GraphQL__Type? return_,
  }) {
    return GraphQL__Field_type((return_ ?? this.return_));
  }

  /// `GraphQL__Field_type` のフィールドを変更したものを新しく返す
  @useResult
  GraphQL__Field_type updateFields({
    GraphQL__Type Function(GraphQL__Type prevReturn_)? return_,
  }) {
    return GraphQL__Field_type(
        ((return_ == null) ? this.return_ : return_(this.return_)));
  }

  @override
  @useResult
  int get hashCode {
    return return_.hashCode;
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return ((other is GraphQL__Field_type) && (return_ == other.return_));
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Field_type(${return_}, )';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return query_string.QueryFieldField(
      'type',
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeObject(return_),
        graphql_type.ListType.notList,
        false,
      ),
    );
  }
}

///
///
/// type: `bool`
@immutable
final class GraphQL__Field_isDeprecated implements GraphQL__Field_Field {
  ///
  ///
  /// type: `bool`
  const GraphQL__Field_isDeprecated();
  @override
  @useResult
  int get hashCode {
    return Object.hashAll([]);
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (other is GraphQL__Field_isDeprecated);
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Field_isDeprecated()';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return const query_string.QueryFieldField(
      'isDeprecated',
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeBoolean(),
        graphql_type.ListType.notList,
        false,
      ),
    );
  }
}

///
///
/// type: `String?`
@immutable
final class GraphQL__Field_deprecationReason implements GraphQL__Field_Field {
  ///
  ///
  /// type: `String?`
  const GraphQL__Field_deprecationReason();
  @override
  @useResult
  int get hashCode {
    return Object.hashAll([]);
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (other is GraphQL__Field_deprecationReason);
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Field_deprecationReason()';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return const query_string.QueryFieldField(
      'deprecationReason',
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeString(),
        graphql_type.ListType.notList,
        true,
      ),
    );
  }
}

/// Arguments provided to Fields or Directives and the input fields of an InputObject are represented as Input Values which describe their type and optionally a default value.
@immutable
final class GraphQL__InputValue implements query_string.GraphQLObjectType {
  /// Arguments provided to Fields or Directives and the input fields of an InputObject are represented as Input Values which describe their type and optionally a default value.
  const GraphQL__InputValue(
    this.fields, {
    this.name = 'GraphQL__InputValue',
  });
  final IList<GraphQL__InputValue_Field> fields;

  /// この構造の型につける型の名前. ※同じ名前で違う構造にするとエラーになるので注意!
  final String name;

  /// `GraphQL__InputValue` を複製する
  @useResult
  GraphQL__InputValue copyWith({
    IList<GraphQL__InputValue_Field>? fields,
    String? name,
  }) {
    return GraphQL__InputValue(
      (fields ?? this.fields),
      name: (name ?? this.name),
    );
  }

  /// `GraphQL__InputValue` のフィールドを変更したものを新しく返す
  @useResult
  GraphQL__InputValue updateFields({
    IList<GraphQL__InputValue_Field> Function(
            IList<GraphQL__InputValue_Field> prevFields)?
        fields,
    String Function(String prevName)? name,
  }) {
    return GraphQL__InputValue(
      ((fields == null) ? this.fields : fields(this.fields)),
      name: ((name == null) ? this.name : name(this.name)),
    );
  }

  @override
  @useResult
  int get hashCode {
    return Object.hash(
      fields,
      name,
    );
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (((other is GraphQL__InputValue) && (fields == other.fields)) &&
        (name == other.name));
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__InputValue(${fields}, name: ${name}, )';
  }

  @override
  @useResult
  IList<query_string.QueryField> toFieldList() {
    return IList(fields.map((field) {
      return field.toField();
    }));
  }

  @override
  @useResult
  String getTypeName() {
    return name;
  }

  @override
  @useResult
  String getDescription() {
    return 'Arguments provided to Fields or Directives and the input fields of an InputObject are represented as Input Values which describe their type and optionally a default value.';
  }
}

/// Arguments provided to Fields or Directives and the input fields of an InputObject are represented as Input Values which describe their type and optionally a default value.
@immutable
sealed class GraphQL__InputValue_Field
    implements query_string.IntoGraphQLField {
  /// Arguments provided to Fields or Directives and the input fields of an InputObject are represented as Input Values which describe their type and optionally a default value.
  const GraphQL__InputValue_Field();
}

///
///
/// type: `String`
@immutable
final class GraphQL__InputValue_name implements GraphQL__InputValue_Field {
  ///
  ///
  /// type: `String`
  const GraphQL__InputValue_name();
  @override
  @useResult
  int get hashCode {
    return Object.hashAll([]);
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (other is GraphQL__InputValue_name);
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__InputValue_name()';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return const query_string.QueryFieldField(
      'name',
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeString(),
        graphql_type.ListType.notList,
        false,
      ),
    );
  }
}

///
///
/// type: `String?`
@immutable
final class GraphQL__InputValue_description
    implements GraphQL__InputValue_Field {
  ///
  ///
  /// type: `String?`
  const GraphQL__InputValue_description();
  @override
  @useResult
  int get hashCode {
    return Object.hashAll([]);
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (other is GraphQL__InputValue_description);
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__InputValue_description()';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return const query_string.QueryFieldField(
      'description',
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeString(),
        graphql_type.ListType.notList,
        true,
      ),
    );
  }
}

///
///
/// type: `type.GraphQL__Type`
@immutable
final class GraphQL__InputValue_type implements GraphQL__InputValue_Field {
  ///
  ///
  /// type: `type.GraphQL__Type`
  const GraphQL__InputValue_type(
    this.return_,
  );
  final GraphQL__Type return_;

  /// `GraphQL__InputValue_type` を複製する
  @useResult
  GraphQL__InputValue_type copyWith({
    GraphQL__Type? return_,
  }) {
    return GraphQL__InputValue_type((return_ ?? this.return_));
  }

  /// `GraphQL__InputValue_type` のフィールドを変更したものを新しく返す
  @useResult
  GraphQL__InputValue_type updateFields({
    GraphQL__Type Function(GraphQL__Type prevReturn_)? return_,
  }) {
    return GraphQL__InputValue_type(
        ((return_ == null) ? this.return_ : return_(this.return_)));
  }

  @override
  @useResult
  int get hashCode {
    return return_.hashCode;
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return ((other is GraphQL__InputValue_type) && (return_ == other.return_));
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__InputValue_type(${return_}, )';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return query_string.QueryFieldField(
      'type',
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeObject(return_),
        graphql_type.ListType.notList,
        false,
      ),
    );
  }
}

/// A GraphQL-formatted string representing the default value for this input value.
///
/// type: `String?`
@immutable
final class GraphQL__InputValue_defaultValue
    implements GraphQL__InputValue_Field {
  /// A GraphQL-formatted string representing the default value for this input value.
  ///
  /// type: `String?`
  const GraphQL__InputValue_defaultValue();
  @override
  @useResult
  int get hashCode {
    return Object.hashAll([]);
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (other is GraphQL__InputValue_defaultValue);
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__InputValue_defaultValue()';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return const query_string.QueryFieldField(
      'defaultValue',
      description:
          'A GraphQL-formatted string representing the default value for this input value.',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeString(),
        graphql_type.ListType.notList,
        true,
      ),
    );
  }
}

///
///
/// type: `bool`
@immutable
final class GraphQL__InputValue_isDeprecated
    implements GraphQL__InputValue_Field {
  ///
  ///
  /// type: `bool`
  const GraphQL__InputValue_isDeprecated();
  @override
  @useResult
  int get hashCode {
    return Object.hashAll([]);
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (other is GraphQL__InputValue_isDeprecated);
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__InputValue_isDeprecated()';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return const query_string.QueryFieldField(
      'isDeprecated',
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeBoolean(),
        graphql_type.ListType.notList,
        false,
      ),
    );
  }
}

///
///
/// type: `String?`
@immutable
final class GraphQL__InputValue_deprecationReason
    implements GraphQL__InputValue_Field {
  ///
  ///
  /// type: `String?`
  const GraphQL__InputValue_deprecationReason();
  @override
  @useResult
  int get hashCode {
    return Object.hashAll([]);
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (other is GraphQL__InputValue_deprecationReason);
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__InputValue_deprecationReason()';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return const query_string.QueryFieldField(
      'deprecationReason',
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeString(),
        graphql_type.ListType.notList,
        true,
      ),
    );
  }
}

/// One possible value for a given Enum. Enum values are unique values, not a placeholder for a string or numeric value. However an Enum value is returned in a JSON response as a string.
@immutable
final class GraphQL__EnumValue implements query_string.GraphQLObjectType {
  /// One possible value for a given Enum. Enum values are unique values, not a placeholder for a string or numeric value. However an Enum value is returned in a JSON response as a string.
  const GraphQL__EnumValue(
    this.fields, {
    this.name = 'GraphQL__EnumValue',
  });
  final IList<GraphQL__EnumValue_Field> fields;

  /// この構造の型につける型の名前. ※同じ名前で違う構造にするとエラーになるので注意!
  final String name;

  /// `GraphQL__EnumValue` を複製する
  @useResult
  GraphQL__EnumValue copyWith({
    IList<GraphQL__EnumValue_Field>? fields,
    String? name,
  }) {
    return GraphQL__EnumValue(
      (fields ?? this.fields),
      name: (name ?? this.name),
    );
  }

  /// `GraphQL__EnumValue` のフィールドを変更したものを新しく返す
  @useResult
  GraphQL__EnumValue updateFields({
    IList<GraphQL__EnumValue_Field> Function(
            IList<GraphQL__EnumValue_Field> prevFields)?
        fields,
    String Function(String prevName)? name,
  }) {
    return GraphQL__EnumValue(
      ((fields == null) ? this.fields : fields(this.fields)),
      name: ((name == null) ? this.name : name(this.name)),
    );
  }

  @override
  @useResult
  int get hashCode {
    return Object.hash(
      fields,
      name,
    );
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (((other is GraphQL__EnumValue) && (fields == other.fields)) &&
        (name == other.name));
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__EnumValue(${fields}, name: ${name}, )';
  }

  @override
  @useResult
  IList<query_string.QueryField> toFieldList() {
    return IList(fields.map((field) {
      return field.toField();
    }));
  }

  @override
  @useResult
  String getTypeName() {
    return name;
  }

  @override
  @useResult
  String getDescription() {
    return 'One possible value for a given Enum. Enum values are unique values, not a placeholder for a string or numeric value. However an Enum value is returned in a JSON response as a string.';
  }
}

/// One possible value for a given Enum. Enum values are unique values, not a placeholder for a string or numeric value. However an Enum value is returned in a JSON response as a string.
@immutable
sealed class GraphQL__EnumValue_Field implements query_string.IntoGraphQLField {
  /// One possible value for a given Enum. Enum values are unique values, not a placeholder for a string or numeric value. However an Enum value is returned in a JSON response as a string.
  const GraphQL__EnumValue_Field();
}

///
///
/// type: `String`
@immutable
final class GraphQL__EnumValue_name implements GraphQL__EnumValue_Field {
  ///
  ///
  /// type: `String`
  const GraphQL__EnumValue_name();
  @override
  @useResult
  int get hashCode {
    return Object.hashAll([]);
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (other is GraphQL__EnumValue_name);
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__EnumValue_name()';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return const query_string.QueryFieldField(
      'name',
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeString(),
        graphql_type.ListType.notList,
        false,
      ),
    );
  }
}

///
///
/// type: `String?`
@immutable
final class GraphQL__EnumValue_description implements GraphQL__EnumValue_Field {
  ///
  ///
  /// type: `String?`
  const GraphQL__EnumValue_description();
  @override
  @useResult
  int get hashCode {
    return Object.hashAll([]);
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (other is GraphQL__EnumValue_description);
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__EnumValue_description()';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return const query_string.QueryFieldField(
      'description',
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeString(),
        graphql_type.ListType.notList,
        true,
      ),
    );
  }
}

///
///
/// type: `bool`
@immutable
final class GraphQL__EnumValue_isDeprecated
    implements GraphQL__EnumValue_Field {
  ///
  ///
  /// type: `bool`
  const GraphQL__EnumValue_isDeprecated();
  @override
  @useResult
  int get hashCode {
    return Object.hashAll([]);
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (other is GraphQL__EnumValue_isDeprecated);
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__EnumValue_isDeprecated()';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return const query_string.QueryFieldField(
      'isDeprecated',
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeBoolean(),
        graphql_type.ListType.notList,
        false,
      ),
    );
  }
}

///
///
/// type: `String?`
@immutable
final class GraphQL__EnumValue_deprecationReason
    implements GraphQL__EnumValue_Field {
  ///
  ///
  /// type: `String?`
  const GraphQL__EnumValue_deprecationReason();
  @override
  @useResult
  int get hashCode {
    return Object.hashAll([]);
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (other is GraphQL__EnumValue_deprecationReason);
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__EnumValue_deprecationReason()';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return const query_string.QueryFieldField(
      'deprecationReason',
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeString(),
        graphql_type.ListType.notList,
        true,
      ),
    );
  }
}

/// A Directive provides a way to describe alternate runtime execution and type validation behavior in a GraphQL document.
///
/// In some cases, you need to provide options to alter GraphQL's execution behavior in ways field arguments will not suffice, such as conditionally including or skipping a field. Directives provide this by describing additional information to the executor.
@immutable
final class GraphQL__Directive implements query_string.GraphQLObjectType {
  /// A Directive provides a way to describe alternate runtime execution and type validation behavior in a GraphQL document.
  ///
  /// In some cases, you need to provide options to alter GraphQL's execution behavior in ways field arguments will not suffice, such as conditionally including or skipping a field. Directives provide this by describing additional information to the executor.
  const GraphQL__Directive(
    this.fields, {
    this.name = 'GraphQL__Directive',
  });
  final IList<GraphQL__Directive_Field> fields;

  /// この構造の型につける型の名前. ※同じ名前で違う構造にするとエラーになるので注意!
  final String name;

  /// `GraphQL__Directive` を複製する
  @useResult
  GraphQL__Directive copyWith({
    IList<GraphQL__Directive_Field>? fields,
    String? name,
  }) {
    return GraphQL__Directive(
      (fields ?? this.fields),
      name: (name ?? this.name),
    );
  }

  /// `GraphQL__Directive` のフィールドを変更したものを新しく返す
  @useResult
  GraphQL__Directive updateFields({
    IList<GraphQL__Directive_Field> Function(
            IList<GraphQL__Directive_Field> prevFields)?
        fields,
    String Function(String prevName)? name,
  }) {
    return GraphQL__Directive(
      ((fields == null) ? this.fields : fields(this.fields)),
      name: ((name == null) ? this.name : name(this.name)),
    );
  }

  @override
  @useResult
  int get hashCode {
    return Object.hash(
      fields,
      name,
    );
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (((other is GraphQL__Directive) && (fields == other.fields)) &&
        (name == other.name));
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Directive(${fields}, name: ${name}, )';
  }

  @override
  @useResult
  IList<query_string.QueryField> toFieldList() {
    return IList(fields.map((field) {
      return field.toField();
    }));
  }

  @override
  @useResult
  String getTypeName() {
    return name;
  }

  @override
  @useResult
  String getDescription() {
    return 'A Directive provides a way to describe alternate runtime execution and type validation behavior in a GraphQL document.\n\nIn some cases, you need to provide options to alter GraphQL\'s execution behavior in ways field arguments will not suffice, such as conditionally including or skipping a field. Directives provide this by describing additional information to the executor.';
  }
}

/// A Directive provides a way to describe alternate runtime execution and type validation behavior in a GraphQL document.
///
/// In some cases, you need to provide options to alter GraphQL's execution behavior in ways field arguments will not suffice, such as conditionally including or skipping a field. Directives provide this by describing additional information to the executor.
@immutable
sealed class GraphQL__Directive_Field implements query_string.IntoGraphQLField {
  /// A Directive provides a way to describe alternate runtime execution and type validation behavior in a GraphQL document.
  ///
  /// In some cases, you need to provide options to alter GraphQL's execution behavior in ways field arguments will not suffice, such as conditionally including or skipping a field. Directives provide this by describing additional information to the executor.
  const GraphQL__Directive_Field();
}

///
///
/// type: `String`
@immutable
final class GraphQL__Directive_name implements GraphQL__Directive_Field {
  ///
  ///
  /// type: `String`
  const GraphQL__Directive_name();
  @override
  @useResult
  int get hashCode {
    return Object.hashAll([]);
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (other is GraphQL__Directive_name);
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Directive_name()';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return const query_string.QueryFieldField(
      'name',
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeString(),
        graphql_type.ListType.notList,
        false,
      ),
    );
  }
}

///
///
/// type: `String?`
@immutable
final class GraphQL__Directive_description implements GraphQL__Directive_Field {
  ///
  ///
  /// type: `String?`
  const GraphQL__Directive_description();
  @override
  @useResult
  int get hashCode {
    return Object.hashAll([]);
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (other is GraphQL__Directive_description);
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Directive_description()';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return const query_string.QueryFieldField(
      'description',
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeString(),
        graphql_type.ListType.notList,
        true,
      ),
    );
  }
}

///
///
/// type: `bool`
@immutable
final class GraphQL__Directive_isRepeatable
    implements GraphQL__Directive_Field {
  ///
  ///
  /// type: `bool`
  const GraphQL__Directive_isRepeatable();
  @override
  @useResult
  int get hashCode {
    return Object.hashAll([]);
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (other is GraphQL__Directive_isRepeatable);
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Directive_isRepeatable()';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return const query_string.QueryFieldField(
      'isRepeatable',
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeBoolean(),
        graphql_type.ListType.notList,
        false,
      ),
    );
  }
}

///
///
/// type: `IList<type.GraphQL__DirectiveLocation>`
@immutable
final class GraphQL__Directive_locations implements GraphQL__Directive_Field {
  ///
  ///
  /// type: `IList<type.GraphQL__DirectiveLocation>`
  const GraphQL__Directive_locations();
  @override
  @useResult
  int get hashCode {
    return Object.hashAll([]);
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (other is GraphQL__Directive_locations);
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Directive_locations()';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return const query_string.QueryFieldField(
      'locations',
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeNotObject('__DirectiveLocation'),
        graphql_type.ListType.list,
        false,
      ),
    );
  }
}

///
///
/// type: `IList<type.GraphQL__InputValue>`
@immutable
final class GraphQL__Directive_args implements GraphQL__Directive_Field {
  ///
  ///
  /// type: `IList<type.GraphQL__InputValue>`
  const GraphQL__Directive_args(
    this.return_, {
    this.includeDeprecated = const query_string.StaticValue(null),
  });
  final query_string.VariableOrStaticValue<bool?> includeDeprecated;

  final GraphQL__InputValue return_;

  /// `GraphQL__Directive_args` を複製する
  @useResult
  GraphQL__Directive_args copyWith({
    query_string.VariableOrStaticValue<bool?>? includeDeprecated,
    GraphQL__InputValue? return_,
  }) {
    return GraphQL__Directive_args(
      (return_ ?? this.return_),
      includeDeprecated: (includeDeprecated ?? this.includeDeprecated),
    );
  }

  /// `GraphQL__Directive_args` のフィールドを変更したものを新しく返す
  @useResult
  GraphQL__Directive_args updateFields({
    query_string.VariableOrStaticValue<bool?> Function(
            query_string.VariableOrStaticValue<bool?> prevIncludeDeprecated)?
        includeDeprecated,
    GraphQL__InputValue Function(GraphQL__InputValue prevReturn_)? return_,
  }) {
    return GraphQL__Directive_args(
      ((return_ == null) ? this.return_ : return_(this.return_)),
      includeDeprecated: ((includeDeprecated == null)
          ? this.includeDeprecated
          : includeDeprecated(this.includeDeprecated)),
    );
  }

  @override
  @useResult
  int get hashCode {
    return Object.hash(
      includeDeprecated,
      return_,
    );
  }

  @override
  @useResult
  bool operator ==(
    Object other,
  ) {
    return (((other is GraphQL__Directive_args) &&
            (includeDeprecated == other.includeDeprecated)) &&
        (return_ == other.return_));
  }

  @override
  @useResult
  String toString() {
    return 'GraphQL__Directive_args(${return_}, includeDeprecated: ${includeDeprecated}, )';
  }

  @override
  @useResult
  query_string.QueryField toField() {
    return query_string.QueryFieldField(
      'args',
      args: IList([
        query_string.QueryFieldArg(
          name: 'includeDeprecated',
          input: includeDeprecatedToQueryInput(),
        )
      ]),
      description: '',
      return_: query_string.GraphQLOutputTypeConsiderListNull(
        query_string.GraphQLOutputTypeObject(return_),
        graphql_type.ListType.list,
        false,
      ),
    );
  }

  @useResult
  query_string.QueryInput includeDeprecatedToQueryInput() {
    return includeDeprecated.toQueryInput(
      type: const graphql_type.GraphQLType(
        name: 'Boolean',
        isNullable: true,
        listType: graphql_type.ListType.notList,
      ),
      staticValueToQueryInputFunc: (staticValue) {
        return (switch (staticValue) {
          null => const query_string.QueryInputNull(),
          final nonNull => query_string.QueryInputBoolean(nonNull),
        });
      },
    );
  }
}
