name: simple_dart_code_gen
description: simple_dart_code_gen
repository: https://github.com/narumincho/dart-packages/tree/main/packages/simple_dart_code_gen
version: "0.5.2"
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  dart_style: ">=2.3.1 <3.0.0"
  fast_immutable_collections: ^9.1.1
  meta: ">=1.9.1 <2.0.0"
  narumincho_util: ^0.1.0
dev_dependencies:
  test: ^1.24.2
