name: simple_dart_code_gen
description: simple_dart_code_gen
repository: https://github.com/narumincho/dart-packages/tree/main/packages/simple_dart_code_gen
version: "0.8.0"
environment:
  sdk: ">=3.5.0 <4.0.0"
dependencies:
  dart_style: ">=3.0.0 <4.0.0"
  fast_immutable_collections: ">=10.0.0 <12.0.0"
  meta: ">=1.9.1 <2.0.0"
  narumincho_util: ^0.3.0
  pub_semver: ^2.1.5
dev_dependencies:
  test: ">=1.25.12 <2.0.0"
