name: narumincho_util
description: narumincho_util
repository: https://github.com/narumincho/dart-packages/tree/main/packages/narumincho_util
version: "0.2.0"
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  collection: ^1.17.1
  fast_immutable_collections: ">=10.0.0 <11.0.0"
  meta: ">=1.9.1 <2.0.0"
dev_dependencies:
  test: ^1.24.2
