name: narumincho_util
description: narumincho_util
repository: https://github.com/narumincho/dart-packages
version: "0.0.2"
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  fast_immutable_collections: "^9.0.0"
  collection: "^1.17.1"
  meta: "^1.8.0"
