name: narumincho_util
description: narumincho_util
repository: https://github.com/narumincho/dart-packages/packages/narumincho_util
version: "0.0.3"
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  collection: ^1.17.0
  fast_immutable_collections: ^9.0.0
  meta: ">=1.8.0 <2.0.0"
dev_dependencies:
  test: ^1.24.2
