name: narumincho_json
description: narumincho_json
repository: https://github.com/narumincho/dart-packages/tree/main/packages/narumincho_json
version: "0.0.2"
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  fast_immutable_collections: ^9.1.1
  meta: ">=1.9.1 <2.0.0"
dev_dependencies:
  test: ^1.24.2
