name: freezed_test
description: freezed_test
repository: https://github.com/narumincho/dart-packages/tree/main/packages/freezed_test
version: "0.1.0"
environment:
  sdk: ">=3.2.0 <4.0.0"
dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
dependencies:
  fast_immutable_collections: ^9.2.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  test: ^1.25.0
