name: test

on:
  pull_request:

jobs:
  flutter-test:
    name: test and analyze
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: dart test ./test/test.dart
        working-directory: packages/narumincho_json
      - run: dart test ./test/test.dart
        working-directory: packages/narumincho_util
      - run: dart test ./test/test.dart
        working-directory: packages/simple_dart_code_gen
      - run: dart test ./test/test.dart
        working-directory: packages/simple_graphql_client_gen
      - name: Analyze Flutter
        uses: ValentinVignal/action-dart-analyze@v0.15
        with:
          fail-on: warning
